version: "3"
services:
 otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./otel-collector/files/metrics.json:/tmp/metrics.json
      - ./otel-collector/files/logs.json:/tmp/logs.json
      - ./otel-collector/files/traces.json:/tmp/traces.json
    ports:
      - "43170:4317"   # OTLP gRPC receiver
      - "43180:4318"   # OTLP http receiver
